name: Build JS Engine

on:
  push:
    branches: [main]
    paths:
      - src/**
      - third-party/**
      - CMakeLists.txt
      - .github/workflows/build.yml
  pull_request:
    branches: [main]
    paths:
      - src/**
      - third-party/**
      - CMakeLists.txt
      - .github/workflows/build.yml
  workflow_dispatch: # 允许手动触发

env:
  BUILD_TYPE: RelWithDebInfo

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Visual Studio Environment
        uses: microsoft/setup-msbuild@v1.3.1

      - name: Configure CMake
        run: |
          cmake -B ${{github.workspace}}/build -S . -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: js_engine-windows-x64-${{env.BUILD_TYPE}}-${{github.sha}}
          path: |
            bin/endstone_js_engine.dll
            bin/endstone_js_engine.pdb